### PR TITLE
Deeper IDE-like integration with Meson

### PR DESCRIPTION
**Pull request by SolarLiner**
I have been working on integrating Meson a little deeper with VS Code. The PR contains the following changes:

- [x] Refactoring of the code structure - this was necessary to keep clean code
- [x] Changes to the task definition schema - this is to allow "build" and "run" types of tasks for the same target
- [x] Use of `meson introspect` as a data source
  - [x] Register a task provider to build targets and run executables
  - [x] New sidebar "tab" (aka. "View Container") with overview of Meson project
    - [x] Targets view with click-to-build feature
      - [x] Also show sources (broken in `meson introspect`)
    - [x] Tests view with click-to-run feature (broken in `meson introspect`)
- [x] Configure Meson on activate (when meson.build in workspace, or opening a meson.build file)
- [x] Extension configuration
  - [x] Configurable build directory
  - [x] Configurable configuration options
- ~~Debug configuration provider (would be nice to automatically configure debug for all executable targets)~~
- [ ] Properly licensed icons (either getting icons with proper license for reuse or make custom ones - the ones in the repo are taken from `vector-of-bool.cmake`)

I've attached a screencast showcasing the workflow with the added changes: ~~[vscode-meson.zip](https://github.com/asabil/vscode-meson/files/3161031/vscode-meson.zip)~~ (outdated)

## Regarding the icons

We need some icons to properly convey the meaning of the different items. I can't draw for the life of me, so I'd need somebody to come in and get some icons for me to use.

**Icons needed**:

- [x] Official Meson logo (provided and licensed by @jpakkane)
- [ ] Executable target
- [ ] Jar target
- [ ] (Static) library
- [ ] Subprojects icon
- [ ] Subproject icon
- [ ] Targets icon
- [ ] Tests icon
- [ ] Run target (optional, can use executable target icon)
- [ ] Custom target (optional, can use the Meson logo)
- [ ] Shared library (optional, can use shared library icon)

### CODE REVIEW

**Comment by asabil** [comment]
This looks amazing! Looking forward to having it merged :)

**Comment by SolarLiner** [comment]
Some more thoughts about debugging. Since Meson supports multiple programming languages but doesn't provide information about how to debug them other than the executable filename, we'd need to know how to debug all supported project types.

Therefore I've removed the debug task off the PR for now, let the user manually set up the debug tasks (having them build before launch is easy now with the Meson tasks), maybe we can add that feature in another PR.

**Comment by SolarLiner** [comment]
Some more progress: 
Capture d’écran de 2019-05-11 02-04-41

Navigating the XServer code (as shown in screenshot) is still lightning fast as VS Code evaluates nodes lazily. Grouping targets and sources by folder makes is more organized, too.

Files have their associated icons, it's just that the development window has no extensions and zero config.

**Comment by SolarLiner** [comment]
Capture d’écran de 2019-05-12 05-15-16

Moved individual TreeViews into a global one. I can't put tests under the subprojects because Meson introspection doesn't expose from which subprojects belong the tests.

I need to stop somewhere, so while I have other ideas, I think I'll work on getting the configuration going, and get proper icons, which, speaking of which, I'll update the PR details with mode details about what I need. Any contribution welcome!

**Comment by SolarLiner** [comment]
To get out of the legal grey area of using somebody else's icons, I've opted to temporarily use Material Design Icons - their icons are SIL licensed but aren't specific enough to cover the cases here.

Capture d’écran de 2019-05-12 05-50-34

Promised, I'll work on the configuration next. :laughing:

**Comment by SolarLiner** [comment]
Configuration: done. With an added bonus:

Note that the progress notification only shows when the command is invoked (through command palette and clicking on targets in the project view) and not when VS Code tasks are run - this is because tasks run ninja directly instead of letting extension control of what's happening.

**Comment by asabil** [comment]
I looked at this work in progress PR, and it looks really neat! I am ready to merge it as soon as you are ready, just let me know!

**Comment by SolarLiner** [comment]
Finally [uploaded the video](https://gfycat.com/decimaldimkilldeer) I wanted to show a comment higher.

@asabil Well, we need a call for the new icons, unless you're happy with using the ones from [MDI](https://materialdesignicons.com/), in which case I have to integrate them for light themes.

**Comment by SolarLiner** [comment]
I've squeezed one last feature: a picker for the Build command to select a target.

And with this, I'm opening up this PR for review, and for merging, if @asabil is okay with the Material Design Icons/

**Comment by SolarLiner** [comment]
@asabil bump

**Comment by asabil** [comment]
This looks amazing! Thank you very much

**Comment by asabil** [comment]
One more thing, I just noticed that the README contains a notice about the cmake icons. These are no longer used, right? So we can remove that notice

**Comment by SolarLiner** [comment]
I thought I had removed the notice on the README - but yes, since the MDI icons are now in use the CMake icons aren't anymore. You can remove that notice.

**Comment by asabil** [comment]
The extension is now updated on the Marketplace. Thanks again for this PR :)

**Pull request merged**
